import type { Metadata } from "next";
import { Comfortaa } from 'next/font/google'
import "./globals.css";
import Navigation from "../components/Navigation";

const comfortaa = Comfortaa({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="bg-slate-900">
      <body translate="no"
        className={`${comfortaa.className} antialiased bg-gradient-to-tr from-slate-200 to-white flex-col`}
      >
        <Navigation />
        {children}

      </body>
    </html>
  );
}