import type { Metadata } from "next";
import { Comfortaa } from 'next/font/google'
import "./globals.css";
import Navigation from "./components/Navigation";
import { FlameIcon } from "lucide-react";
import NavMenu from "./components/NavMenu";

const comfortaa = Comfortaa({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body translate="no"
        className={`${comfortaa.className} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
